### ISSUE TITLE
Friend removal

### ISSUE THREAD

**Issue by m-urce** [roblox-plus/extension#10]
When I first started using this Chrome Extension which was about a year or 2 ago I started noticing that whenever I wanted to unfriend someone on Roblox the profile page of the person I try to unfriend goes darker and the 'Confirm Action' pop up becomes unclickable (This only happens with this Chrome Extension being on).

I thought a fix to this would be really needed as a lot of people using this Extension are traders and to trade you are mostly required to friend people depending on their settings.

**Comment by vftable** [comment]
Its simple how to fix this. Click inspect element on the dark screen and delete the element.

**Comment by SR5297WAKELIN** [comment]
It would be better that we don't have to keep using inspect element every time to remove a friend.

**Comment by glaqss** [comment]
Click F5 on your keyboard, Hover over the unfriend button, spam click it. I know that it has worked for me.

**Comment by juls0730** [comment]
@m-urce it seems that the bug was mentioned in #20 and supposedly fixed the issue, is this issue still relevant or has it just not been closed?

**Comment by WebGL3D** [comment]
The extension use to have a feature a "confirm" feature before allowing you to remove your friend, but it broke. That feature was indeed removed by #20.
