### ISSUE TITLE
Group Revenue Chart

### ISSUE THREAD

**Issue by alreadypro** [roblox-plus/extension#14]
The group revenue chart does not work, despite letting it load all of the transactions.

I am 100% positive that I had revenue this day.

![image](https://user-images.githubusercontent.com/27824159/107737756-0cd5ff00-6cba-11eb-91eb-521f9d7a8120.png)

**Comment by WebGL3D** [comment]
Replaced by new [transactions page](https://roblox.plus/transactions), with #90.
