### ISSUE TITLE
robux

### ISSUE THREAD

**Issue by missiacat** [roblox-plus/extension#15]

**Comment by just-a-github-user** [comment]
no

**Comment by JS101dotgit** [comment]
No bobux 🤯 for u

**Comment by just-a-github-user** [comment]
> No bobux 🤯 for u

wait no plssssssssssssss plssssssssssss i really need bobux plssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssss give 23748236846827349827384623874728346726384 bobux pls pls pls pls plssssssssssssssssssssssssssss
