### ISSUE TITLE
Group notifications not working

### ISSUE THREAD

**Issue by KingKusuo** [roblox-plus/extension#19]
I've configured everything to get notified when a certain group changes their shouts, but nothing seems to work, i've pressed the disaster recovery button, and that didn't work, i've looked at the extension page on my browser, and notifications are on too, so i really just want to fix that.
![imagem_2021-08-12_012942](https://user-images.githubusercontent.com/69478539/129138400-d5c7b343-fc2f-4117-b292-be6d9b8011ee.png)

**Comment by KingKusuo** [comment]
I see it has been fixed, thank you oc!

**Comment by WebGL3D** [comment]
Thanks for confirming!
