### ISSUE TITLE
Control Panel displays blank page

### ISSUE THREAD

**Issue by CombatSwift** [roblox-plus/extension#27]
Control panel does not load at all, only displaying a blank roblox screen. No matter what is done, disabling other extensions, other browsers, even other accounts, it still will not load. 
![4533333333332334](https://user-images.githubusercontent.com/35820615/129752622-d3a2d2f4-f294-4da9-9d4c-88e402b0f63e.PNG)

**Comment by policetonyR** [comment]
Having the same issue.

**Comment by juls0730** [comment]
is this issue still relevant? @CombatSwift if this issue is still relevant please put any console errors here (ctrl+shift+j)

**Comment by CombatSwift** [comment]
It is, and the error is "DevTools failed to load source map: Could not load content for chrome-extension://jfbnmfgkohlfclfnplnlenbalpppohkm/js/vendors/highcharts.js.map: HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME"

**Comment by juls0730** [comment]
@CombatSwift so devtools seems to have not loaded that javscript file because its not a know url scheme? are you using chrome or are you using a chromium-based browser (ex: brave, vivaldi, opera, edge)

**Comment by CombatSwift** [comment]
@juls0730 Chrome Dev

**Comment by WebGL3D** [comment]
This should be resolved. :sweat_smile:
