### ISSUE TITLE
Premium features can be accessed with Inspect Element

### ISSUE THREAD

**Issue by antonio6643** [roblox-plus/extension#3]
If you remove the `disabled` tag from a premium feature in the Roblox+ settings tab, you'll be able to click it and apply it.

**Comment by WebGL3D** [comment]
Fixed by popular demand with https://github.com/Roblox-Plus/Chrome/commit/8b72bff9ee74012aa4a957ca842c22ebdd69482c

**Comment by ha6000** [comment]
@WebGL3D it can still be enabled if you edit the code, either through cloning and rebuilding it or through inspect element. but this is unfixable. you can make it harder to do but will always be possible. there isn't a way to limit the client. but nice try
