### ISSUE TITLE
Item Owners Tab

### ISSUE THREAD

**Issue by Conkley** [roblox-plus/extension#7]
The owners tab shows everyone as deleted and does not load pages after the 1st one.

**Comment by WebGL3D** [comment]
Roblox released an inventory privacy setting which makes it impossible to tell the difference between someone who is no longer on the platform and someone who just has their inventory when pulling the owners.
Proposed "fix": change wording for owners list to mention the user has their inventory hidden (more common than the user being permanently banned).

**Comment by WebGL3D** [comment]
Updated text for hidden inventories in 2.2.91.
