### ISSUE TITLE
Add link to this repo on the Chrome store's page for this extension

### ISSUE THREAD

**Issue by ghost** [roblox-plus/extension#9]
All this time I've assumed that your extension is closed source as from the Chrome extension page for this, as there's no link that leads here.

Could a link to this repository be added to the Chrome store page for this please so that further confusion isn't caused? For other projects like Ublock Origin, the GitHub repo is linked to.

**Comment by WebGL3D** [comment]
The GitHub repository is linked as the "website" on the chrome extension page, similarly the privacy policy links back to the repository ([PrivacyPolicy.md](https://github.com/roblox-plus/chrome/blob/master/PrivacyPolicy.md)).
